name: IoT
favicon: null
layout_spectrum: 0.016348975710570812
typography_spectrum: 0.7748427181504667
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.679784033447504
  lightness: 0.8186695219483227
  saturation: 0.6468708743341267
  rhythmicContrast: 0.4078509355895221
purpose: []
